# Generated by Django 5.1.6 on 2025-03-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0002_authors_profile_author_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=5, unique=True)),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_content', models.TextField(blank=True, null=True)),
                ('book_published_at', models.DateTimeField(auto_now_add=True)),
                ('book_updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.authors_profile')),
            ],
        ),
    ]
