# Generated by Django 5.1.6 on 2025-03-12 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='all_books',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AddField(
            model_name='all_books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Rented_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('return_at', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_books', to='books.all_books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
