# Generated by Django 5.1.6 on 2025-02-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_img', models.ImageField(upload_to='author_uploads/')),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_mob', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('author_email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('author_education', models.CharField(blank=True, max_length=100, null=True)),
                ('author_books', models.TextField(blank=True, null=True)),
                ('author_created_at', models.DateTimeField(auto_now=True)),
                ('author_update_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
