# Generated by Django 5.1.6 on 2025-02-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors_profile',
            name='author_about',
            field=models.TextField(default='About Me', null=True),
        ),
        migrations.AlterField(
            model_name='authors_profile',
            name='author_name',
            field=models.CharField(max_length=200),
        ),
    ]
